In [2]:
import numpy as np

a = [1, 2, 3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a, dtype = str)
print(b)

['1' '2' '3' '5' '4.5']


In [4]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a * 3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [5]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [6]:
b = np.ones((2, 3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [7]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [8]:
b = np.zeros((3, 4))
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [9]:
b = np.full((3, 3), 5, dtype = float)
b

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [10]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b = np.arange(2, 10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b = np.arange(2, 20, 2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
b = np.linspace(2, 10)
b
print(b[1] - b[0])
print(b[3] - b[2])

0.163265306122
0.163265306122


In [33]:
b = np.linspace(2, 10, 5, dtype = int, endpoint = False)
b

array([2, 3, 5, 6, 8])

In [34]:
b = np.identity(3)
b

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [36]:
b = np.eye(3, 4)
b

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [61]:
b = np.random.rand(3)
b

array([ 0.26949561,  0.06503371,  0.29373579])

In [66]:
b = np.random.rand(10)*10
b

array([ 9.49183749,  8.36951039,  6.19188291,  9.82127093,  6.97574587,
        4.00180958,  4.79949638,  6.74820971,  6.62471485,  8.77169984])

In [62]:
b = np.random.rand(2, 3)
b

array([[ 0.82563547,  0.6411471 ,  0.75633672],
       [ 0.73608608,  0.49069966,  0.72339434]])